version: 2
updates:
  - package-ecosystem: pip
    directories:
      - /dev/breeze
    schedule:
      interval: daily

  - package-ecosystem: pip
    directories:
      - /providers/a/
      - /providers/b/
    schedule:
      interval: daily
    groups:
      provider[a|b]-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directories:
      - /providers/c/
    schedule:
      interval: daily
    groups:
      provider[c]-dependencies:
        patterns:
          - "*"