version: 2
updates:
  - package-ecosystem: pip
    directories:
      - /dev/breeze
    schedule:
      interval: daily

  - package-ecosystem: pip
    directories:
      - /providers/a/
      - /providers/b/
    schedule:
      interval: daily
    groups:
      provider-one-dependencies:
        patterns:
          - "*"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"

  - package-ecosystem: pip
    directories:
      - /providers/c/
    schedule:
      interval: daily
    groups:
      provider-two-dependencies:
        patterns:
          - "*"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"